/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pavle_vukovic_memorygame_JNIexample */

#ifndef _Included_pavle_vukovic_memorygame_JNIexample
#define _Included_pavle_vukovic_memorygame_JNIexample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pavle_vukovic_memorygame_JNIexample
 * Method:    points
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_pavle_vukovic_memorygame_JNIexample_points
  (JNIEnv *, jobject, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
